USE [master]
GO

/****** Object:  Database [WatchKSL]    Script Date: 5/27/2013 5:18:26 PM ******/
CREATE DATABASE [WatchKSL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WatchKSL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.CHENLOCALSQL\MSSQL\DATA\WatchKSL.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WatchKSL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.CHENLOCALSQL\MSSQL\DATA\WatchKSL_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WatchKSL] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WatchKSL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WatchKSL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WatchKSL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WatchKSL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WatchKSL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WatchKSL] SET ARITHABORT OFF 
GO

ALTER DATABASE [WatchKSL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WatchKSL] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [WatchKSL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WatchKSL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WatchKSL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WatchKSL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WatchKSL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WatchKSL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WatchKSL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WatchKSL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WatchKSL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WatchKSL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WatchKSL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WatchKSL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WatchKSL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WatchKSL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WatchKSL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WatchKSL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WatchKSL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WatchKSL] SET  MULTI_USER 
GO

ALTER DATABASE [WatchKSL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WatchKSL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WatchKSL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WatchKSL] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WatchKSL] SET  READ_WRITE 
GO


USE [WatchKSL]
GO

/****** Object:  Table [dbo].[Customer]    Script Date: 5/27/2013 5:19:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Customer](
	[CustomerId] [bigint] IDENTITY(1,1) NOT NULL,
	[Email] [varchar](100) NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[CustomerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [WatchKSL]
GO

/****** Object:  Table [dbo].[SearchQueue]    Script Date: 5/27/2013 5:19:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SearchQueue](
	[CustomerId] [bigint] NOT NULL,
	[Keyword] [varchar](250) NULL,
	[PriceMin] [float] NULL,
	[PriceMax] [float] NULL,
	[Status] [bit] NULL,
	[QueueDate] [date] NULL,
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_SearchQueue] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SearchQueue]  WITH CHECK ADD  CONSTRAINT [FK_SearchQueue_Customer] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([CustomerId])
GO

ALTER TABLE [dbo].[SearchQueue] CHECK CONSTRAINT [FK_SearchQueue_Customer]
GO


USE [WatchKSL]
GO

/****** Object:  Table [dbo].[SearchResult]    Script Date: 5/27/2013 5:19:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SearchResult](
	[CustomerId] [bigint] NOT NULL,
	[Title] [varchar](100) NULL,
	[Description] [varchar](250) NULL,
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_SearchResults] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SearchResult] ADD  CONSTRAINT [DF__SearchRes__Creat__1367E606]  DEFAULT (getdate()) FOR [CreatedDate]
GO

ALTER TABLE [dbo].[SearchResult]  WITH CHECK ADD  CONSTRAINT [FK_SearchResults_Customer] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([CustomerId])
GO

ALTER TABLE [dbo].[SearchResult] CHECK CONSTRAINT [FK_SearchResults_Customer]
GO



