//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResult
    {
        public Nullable<long> CustomerId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public long Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
